### ISSUE TITLE
Saving frame positions via ctrl+click

### ISSUE THREAD

**Issue by the-rebel-Mermaid** [the-rebel-Mermaid/BlizzMove#17]
[From garak8402 on WoWI:](https://www.wowinterface.com/downloads/addcomment.php?action=addcomment&fileid=25092&quote=483317)

Hi there, longtime Blizzmove user here:).  I used to love when this addon had the ctrl+click feature to save frame positions.  I eventually used MoveAnything to achieve this, but there isn't a working version for Classic that I'm yet aware of.  So I got to messing around with the old files on curseforge and found that (to a large extent) version 1.4 still works!  

[version 1.4 on curse](https://www.curseforge.com/wow/addons/blizzmove/files/884527)

Everything moves, scales and saves positions fine EXCEPT for the talent frame.  There may be more but that's the only one I noticed.  It does throw an error, but only initially upon logging in.  As a suggestion, unless it's impossible to fix, is this something that can be reimplemented in a future update?  Thanks!!

**Comment by zaCade** [comment]
I got some code that I'm using locally to achieve something similar. Could be useful. Although its kinda broken due to the mover frames change we implemented.

**Comment by Numynum** [comment]
@zaCade 
if you share the code we could see if we can make something out of it I'm sure ^^
do you have any suggestions on a chat somewhere?

**Comment by the-rebel-Mermaid** [comment]
Discord?

**Comment by Numynum** [comment]
it's implemented now :)
