### ISSUE TITLE
If there is at least one World Quest tracked only that section is Visible, normal quest list is gone.

### ISSUE THREAD

**Issue by the-rebel-Mermaid** [the-rebel-Mermaid/BlizzMove#21]
From the curseforge comments:

> Moving the Quest objectives still causing issue.
> If there is at least one World Quest tracked only that section is Visible, normal quest list is gone.
> If Untracking all World Quest only that time can see normal quests.
> Only fix is to delete the Objective frame section from locale-layout file.
> 
> Only fix is to delete the Objective frame section from locale-layout file.

**Comment by the-rebel-Mermaid** [comment]
Can anyone reproduce this?

**Comment by Numynum** [comment]
I've not had any issues myself, with any combination of quests/worldquests
reloadui not fixing it makes me think there's another addon which messes it up

**Comment by Sinakra** [comment]
I also have this issue, but it does not require me to track a world quest, it acts as though tracker has had its window shrunk to only show one quest at a time (two if there is no active World Quests).
Deleting my Character's WTF file fixes the issue for a day, but it returned when I tracked a pet battle world quest.

**Comment by Numynum** [comment]
@Sinakra do you have any other addon that interacts with the quest tracker?
this includes addons like elvui and similar 
also, does this happen after you move the tracker? Or also if you don't touch the position?

**Comment by GnaXi** [comment]
I'm having issues with the Quests tracker as wel.
For some reason it won't allow me to show more than 3 quests at the time.
As soon as I disable BlizzMove, everything is back to normal.

**Comment by Sinakra** [comment]
it will happen regardless of contact with the tracker, moving the tracker will not fix the issue, it may possibly have connections to achievements or addons that affect achievement tracking

**Comment by zaCade** [comment]
Closing this issue, since these frames are removed/disabled atm.
