### ISSUE TITLE
add an option to disable move handle buttons

### ISSUE THREAD

**Issue by Daeveren** [the-rebel-Mermaid/BlizzMove#24]
Somehow, BlizzMove added this red arrow which acts as a collapse button for the objective tracker. Please add an option to have this UI element removed.

**Comment by Numynum** [comment]
it's not a collapse button, you can use it to move the objective tracker

**Comment by Daeveren** [comment]
**it is** a collapse button - when I click it it collapses the entire objective tracker. When I drag it it doesn't move the objective tracker. But anyway....
Point is, it's an UI element from BlizzMove and it can't be hidden, unless the entire addon is disabled. Please add an option to hide this new, red UI element.

**Comment by Numynum** [comment]
![image](https://user-images.githubusercontent.com/17293527/74684631-b29c7e00-51cc-11ea-9364-b38ace24c35b.png)
there are 2 icons
the left one is the default collapse icon, which isn't added by this addon
the red right one is the mover icon, which IS added by this addon

this addon simply put is incapable of collapsing any UI elements; there's no code for it, and collapsing UI elements isn't something blizzard decides to do just because a button looks a certain way

I'll change this issue into a request to toggle/opt out of the mover button

**Comment by Daeveren** [comment]
Alright, so the collapse might be due to some invisible button on my UI.
But thank you a lot for considering hiding of the arrow button!

**Comment by the-rebel-Mermaid** [comment]
Maybe there is a glitch that makes the mover merge with the collapse. 
Did you try if you have the issue just with BlizzMove enabled on an other toon?

**Comment by Daeveren** [comment]
My issue is not the collapse behavior (which might be an invisible button from another addon), the issue at hand is the red button with the yellow arrrow, which I'd like to have an option to hide (it was quite odd to find out that BlizzMove shows it, ass I was not aware that the addon draws anything on the screen).

![Untitled](https://user-images.githubusercontent.com/6321337/74763709-f48afa00-5288-11ea-90f8-97060b2f632d.png)


Just for the sake of it, a /fstack of the button (and again, I have no issue with whatever addon there might be there doing the collapse, I only want to hide the red icon)

![10v8FQbOh3](https://user-images.githubusercontent.com/6321337/74763931-606d6280-5289-11ea-9c18-71974e44978b.png)

**Comment by Numynum** [comment]
that's interesting.. it seems like the move button is overlapping the collapse button
do you see the collapse button (not the red arrow) if you disable BlizzMove?

BlizzMove added the red arrow button relatively recently, to allow people to move frames which don't have a regular title bar (like the objective tracker)

this is what I'd expect on the frame stack (seeing BlizzMoveHandleObjectiveTrackerFrame, but not ObjectiveFrackerFrame.HeaderMenu.MinimizeButton)
![image](https://user-images.githubusercontent.com/17293527/74764772-a07d1700-5282-11ea-869a-44ec14c4f352.png)

**Comment by Daeveren** [comment]
My collapse button (and the objective tracker title bar) are hidden by Chinchilla Minimap - and it seems Chinchilla keeps the collapse button there, just completely hidden.

Normal view (with my settings)
![sKgoSR3Fm7](https://user-images.githubusercontent.com/6321337/74766325-ceb42400-528d-11ea-905e-98d9ae044b09.png)

Chinchilla settings
![9o71XPcX2o](https://user-images.githubusercontent.com/6321337/74766227-a0cedf80-528d-11ea-8865-5cd16fcee7a5.png)

Collapse button enabled (at this point it's being shown on top of BlizzMove's button)
![J6CXfY4cAP](https://user-images.githubusercontent.com/6321337/74766252-acbaa180-528d-11ea-8a1c-555a1eb80cb7.png)

Both collapse and show title enabled
![aHHFk3cv8W](https://user-images.githubusercontent.com/6321337/74766269-b6dca000-528d-11ea-813c-4abba28a6564.png)

**Comment by Numynum** [comment]
that explains it :)
I'm curious why the buttons overlap though; is the objective tracker directly on the edge of your screen? no room for even a small button next to it?

**Comment by Daeveren** [comment]
I think the objective tracker is attached to the minimap, which, indeed, is attached directly to the edge of the screen.

**Comment by Numynum** [comment]
in the current BlizzMove alpha release, all movehandles have been removed
there's a chance it will come back as an optional feature, but this has been disabled by default :)
