### ISSUE TITLE
Option to blacklist windows

### ISSUE THREAD

**Issue by audiosmith** [the-rebel-Mermaid/BlizzMove#25]
This addon can move the loot window, but I have it set to open at cursor. Often I can accidentally move the loot window and cause this addon to override my setting to have it show at cursor, meaning I have to shift+click the loot window to reset positioning.

This really becomes an issue when the loot window keeps closing before I can shift click it.

My suggestion is to have a list of currently modified windows, and an option there to reset the window and blacklist it from being modified in future.

**Comment by zaCade** [comment]
We are currently rewriting the addon so we can add a option panel and some other features, so in the future you'll be able to disable the addon from touching frames ect. For now however you can only really 'edit' the addon so the frames you want 'disabled' aren't in the list.

For the current frame you are having issues with, open up BlizzMove.lua with a text editor and simply remove the line for `LootFrame` that should disable it for now. ^^

**Comment by Numynum** [comment]
You can now do this in the BlizzMove 3.0.0-alpha2 release :) (available from twitch client soon)
