### ISSUE TITLE
way to disable possition saving

### ISSUE THREAD

**Issue by Grandeeney** [the-rebel-Mermaid/BlizzMove#27]
Lately Blizzmove started to safe it's possition so anytime i even accidentaly move a window i have to shift click to reset the position (or it resets with reload) It never did it before always when i turned off the window it used to reset. Also, as far as i know the addon should not save positions at all. Is there a way to prevent this?

**Comment by Numynum** [comment]
this is a feature we added a while back; and we're planning on making it optional later on
for now you can open the Handle.lua file, look for `if self.BlizzMoveBypassHook then return end` and replace it with `if true then return end`
that should disable the saving

**Comment by Grandeeney** [comment]
Perfect, thanks you for responding.
