### ISSUE TITLE
Lua Error on levelUpDisplay. Results in broken UI Element

### ISSUE THREAD

**Issue by nbalaguer** [the-rebel-Mermaid/BlizzMove#28]
**Pastebin** of error [here](https://pastebin.com/wcn5UpW5)

**Addon version:** BlizzMove-v2.1.5.zip (Release)

**Screenshot** of the frame after the error:

![image](https://user-images.githubusercontent.com/3876046/86514071-a299d980-be0f-11ea-826f-6ed972c72be4.png)

"/reloadui" seems to fix it.

In normally occurs when I load into instanced content (visions, m+, raid)

**Comment by Numynum** [comment]
Just to check, this problem doesn't occur when BlizzMove is disabled?
do you have any other addons that interact with the LevelUpDisplay?

I personally have never seen this issue

**Comment by nbalaguer** [comment]
I tested some things today, and have been able to consistently get the error.

After trying disabling and enabling some addons to see if there's any weird interaction happening, I disabled all the addons and only enabled BlizzMove and I got the error too.

To reproduce, for me, these are the steps:

1- esc->addons->disable blizzmove and reloadUI
2- esc->addons->enable blizzmove and reloadUI
3- Queue for an horrific vision->accept queue to access vision lobby (where you put on the masks before activating the vial)

In that lobby, just as you enter, the levelupdisplay appears with the text "Vision of Ogrimmar/Stormwind. Speak with wrathion to enter" something like that. Before it goes away, click and move the frame to any new location.

4. Exit the lobby and return to the chamber of heart, then queue up again and enter again. After the loading screen, I get the error and the display now looks like in the image from first comment.

As a note, after disabling and enabling blizzmove, if I don't move that uiframe, I never get the error, it's only after I move it that I get it the next time it appears.

**Comment by Numynum** [comment]
Thanks for the thourough testing, we'll look into it :)

**Comment by zaCade** [comment]
Removed the ability to move this frame for now, will have to consider either fully removing it or finding a way to fix this issue, incase we readd it.

**Comment by the-rebel-Mermaid** [comment]
> Removed the ability to move this frame for now, will have to consider either fully removing it or finding a way to fix this issue, incase we readd it.

I guess this can be closed then? :)
