### ISSUE TITLE
Can't move or resize the Enchanting window.

### ISSUE THREAD

**Issue by Brunn0121** [the-rebel-Mermaid/BlizzMove#29]
The title says it all, other than that, I haven't found any other issues, this is an awesome addon overall.

**Comment by Numynum** [comment]
Never seen that myself personally
Do you have any addons that alter the enchanting frame?
A thing you can try is disabling every addon except blizzmove, see if there's still an issue
if it's fixed, enable a couple addons at a time until it's broken again and you find the culprit

**Comment by Brunn0121** [comment]
I just disabled every addon I have except for blizzmove and the enchanting tab still don't move or resize :/
Here's a video of the problem: https://youtu.be/TkdlDwIIXTM

**Comment by Brunn0121** [comment]
I just disabled every addon I have installed except for blizzmove and the enchanting window still don't move or resize, here's a video of the problem: https://youtu.be/cl6aldMYDAI

**Comment by Numynum** [comment]
@Brunn0121 is this on wow classic?
I personally don't play that, maybe @zaCade can have a look if he does

**Comment by zaCade** [comment]
Seems that for some reason blizzard decided to make the CraftFrame load on demand while it isn't in retail, no clue why. Fixed now.

**Comment by Brunn0121** [comment]
Yes, it is WoW classic, I forgot to mention it, sorry about that 😅
Wow, it's already fixed, thank you!

**Comment by placentajuan23** [comment]
I am having this same issue in TBC Classic; no other addons except Blizzmove loaded and the enchanting UI is the only one i cant re-size or move. the enchanting frame UI is still named CraftFrame and this frame is not listed in the Blizzmove options to disable/enable only TradeSkillFrame

**Comment by zaCade** [comment]
> 
> 
> I am having this same issue in TBC Classic; no other addons except Blizzmove loaded and the enchanting UI is the only one i cant re-size or move. the enchanting frame UI is still named CraftFrame and this frame is not listed in the Blizzmove options to disable/enable only TradeSkillFrame
> 
> great addon though!

Should be fixed in v3.0.19a, this issue was however from pre v3, so this is sortof a diffrent issue. Fixed it regardless.

**Comment by placentajuan23** [comment]
perfect. many thanks!
