### ISSUE TITLE
CinematicFrame moveable why?!

### ISSUE THREAD

**Issue by fuba82** [the-rebel-Mermaid/BlizzMove#36]
hi there,  
why the "CinematicFrame" is moveable?  

i know i can disable it in the lua but it eludes my understanding why this is moveable at all ^^  
because it just moves the Top and Bottom Border while a Cinematic is active and meanwhile SHIFT + Click does now work!

greetings

**Comment by Numynum** [comment]
in the alpha versions that's no longer possible already; this version will be release with prepatch
