### ISSUE TITLE
Make barbershop window locked

### ISSUE THREAD

**Issue by Neurotoxin001** [the-rebel-Mermaid/BlizzMove#37]
When I came to barber I can't move view with mouse because all controls is moving with background

v 3.0.0

**Comment by Numynum** [comment]
works fine for me, I'm assuming this is in prepatch, not ptr or beta?
when you open up the new BlizzMove config (type `/bm`), do you see `BarberShopFrame` or `Blizzard_BarbershopUI` in the list?

**Comment by Neurotoxin001** [comment]
Ah yes, seems like it's been fixed in 3.0.0 and I tested it in previous version
