### ISSUE TITLE
broken scrolling via mouse wheel in dungeon journal

### ISSUE THREAD

**Issue by rml9ty** [the-rebel-Mermaid/BlizzMove#38]
you can't use scroll wheel in the dungeon journal. nothing is happening. (when trying to scroll down a list of bosses in a raid for example)

**Comment by Numynum** [comment]
this is something we're fixing soon, thanks for the heads up :)

**Comment by Numynum** [comment]
v3.0.1-alpha should be downloadable soon, the issue should be fixed there, let us know if it isn't working right
additionally, more of the encounter journal can be dragged and zoomed in/out

**Comment by rml9ty** [comment]
new version works great! scrolling working, still draggable. thanks!
