### ISSUE TITLE
Can't type in Submit a Bug window

### ISSUE THREAD

**Issue by jasonfromearth** [the-rebel-Mermaid/BlizzMove#41]
On WoW Live (not Beta) I am unable to type in the Submit a bug window when BlizzMove is enabled.
I installed the mod via Twitch client.

Installed version: 3.0.1
Game Version: 9.0.01

**Comment by Numynum** [comment]
we couldn't reproduce this, and it would be highly unlikely for BlizzMove to do this

what I did notice when testing this, is that you have to click the very first line of the textbox to start typing
all the rest of the textbox will just move the whole window

after disabling BlizzMove the same thing happened, that only clicking the first line allowed me to type; but obviously the frame wouldn't move if I dragged anywhere else
